Add meta_{create,update}_date fields to bib_organismes
PnX-SI/UsersHub-authentification-module pull request #99
Opened 2024-05-20 09:12 UTC by lpofredc

Fix [UsersHub/#215](https://github.com/PnX-SI/UsersHub/issues/215)

2024-12-05 23:46 UTC, lpofredc commented
Salut, y a-t-il un point bloquant au merge de cette PR ?

2024-12-06 05:55 UTC, camillemonchicourt commented
Non, c'est à intégrer en effet.

2025-01-02 14:24 UTC, jacquesfize requested changes
Pour moi, c'est bon :+1:  Il faut juste mettre à jour l'identifiant de la révision précédent la nouvellement créée.  Normalement, c'est ce qui fait planter les tests.

2025-01-02 14:24 UTC, jacquesfize commented on src/pypnusershub/migrations/versions/cf38131bc247_add_meta_create_insert_date_to_.py
> +Revises: f9d3b95946cd
```suggestion
Revises: b7c98935d9e8
```

2025-01-02 14:24 UTC, jacquesfize commented on src/pypnusershub/migrations/versions/cf38131bc247_add_meta_create_insert_date_to_.py
> +down_revision = "f9d3b95946cd"
```suggestion
down_revision = "b7c98935d9e8"
```

2025-01-02 14:24 UTC, jacquesfize commented on docs/changelog.rst
> +unreleased (2024-05-xx)
```suggestion
3.0.2 (unreleased)
```

2025-02-10 13:39 UTC, jacquesfize commented on docs/changelog.rst
> +- Ajout des champs `meta_create_date` et `meta_update_date` à la table `bib_organismes` (#96).
```suggestion
```

2025-02-10 13:42 UTC, merged

2025-02-10 14:51 UTC, lpofredc commented
Merci !